### ISSUE TITLE
Error playing few videos

### ISSUE THREAD

**Issue by dheerajbred** [LecleVietnam/LeclePackageIssue#29]
Hi, I tried playing a custom video with headers but getting this error. The video is playing fine on exoplayer. This is the code and the log. 

![image](https://github.com/LecleVietnam/LeclePackageIssue/assets/46578244/133df196-6e01-4f0f-a115-0a8c0ae39ab4)

` Parsed url data end : wgccykhy20~GCkjnNkQgP
I/flutter (10911): urlEnd: null
I/flutter (10911): --- Player status ---
I/flutter (10911): play url : https://dc571so.dood.video/u5kjzwzuttelsdgge44dkiqrdu3lgtsmt6wkmdfogqtl22mkjx7esmcy6kpa/wgccykhy20~GCkjnNkQgP?token=677mhvhizuzx4f5scoz1ozs8&expiry=1691621429100
I/flutter (10911): offline : false
I/flutter (10911): --- start playing –––
I/flutter (10911): ---- m3u8 fitch start ----
I/flutter (10911): https://dc571so.dood.video/u5kjzwzuttelsdgge44dkiqrdu3lgtsmt6wkmdfogqtl22mkjx7esmcy6kpa/wgccykhy20~GCkjnNkQgP?token=677mhvhizuzx4f5scoz1ozs8&expiry=1691621429100
I/flutter (10911): --- please wait –––
I/flutter (10911): --- Current Video Status ---
I/flutter (10911): offline : false
I/System.out(10911): Keeping screen on 
D/CCodecBuffers(10911): [c2.android.aac.decoder#27:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
D/CCodecBuffers(10911): [c2.android.aac.decoder#27:1D-Input.Impl[N]] codec released a buffer owned by client (index 1)
D/CCodecBuffers(10911): [c2.android.aac.decoder#27:1D-Input.Impl[N]] codec released a buffer owned by client (index 2)

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following LateError was thrown building YoYoPlayer(dirty, state: _YoYoPlayerState#b6dac(ticker
inactive)):
LateInitializationError: Field 'controller' has not been initialized.

The relevant error-causing widget was:
  YoYoPlayer
  YoYoPlayer:file:///Volumes/WD%20Thunderbolt%20SSD/Files/Flutter/Flutter%20Apps/Repo%20Apps/lecle_yoyo_player-0.0.6/example/lib/main.dart:42:18

When the exception was thrown, this was the stack:
#0      _YoYoPlayerState.controller (package:lecle_yoyo_player/src/video.dart)
#1      _YoYoPlayerState.build (package:lecle_yoyo_player/src/video.dart:336:14)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5242:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
...     Normal element mounting (28 frames)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#37     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#38     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (324 frames)
#362    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#363    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6570:36)
#364    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6582:32)
...     Normal element mounting (454 frames)
#818    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#819    Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#820    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1240:16)
#821    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1209:5)
#822    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1156:18)
#823    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2720:19)
#824    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1155:13)
#825    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:988:7)
#826    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:968:7)
#830    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════

D/CCodecBuffers(10911): [c2.android.aac.decoder#27:1D-Input.Impl[N]] codec released a buffer owned by client (index 1)
D/CCodecBuffers(10911): [c2.android.aac.decoder#27:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
E/flutter (10911): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'controller' has not been initialized.
E/flutter (10911): #0      _YoYoPlayerState.controller (package:lecle_yoyo_player/src/video.dart)
E/flutter (10911): #1      _YoYoPlayerState.videoControlSetup (package:lecle_yoyo_player/src/video.dart:758:5)
E/flutter (10911): #2      _YoYoPlayerState.urlCheck (package:lecle_yoyo_player/src/video.dart:607:9)
E/flutter (10911): #3      _YoYoPlayerState.initState (package:lecle_yoyo_player/src/video.dart:257:5)
E/flutter (10911): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5219:55)
E/flutter (10911): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter (10911): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter (10911): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter (10911): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6435:14)
E/flutter (10911): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter (10911): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter (10911): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter (10911): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter (10911): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter (10911): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter (10911): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter (10911): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter (10911): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter (10911): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter (10911): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter (10911): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter (10911): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter (10911): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter (10911): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter (10911): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter (10911): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter (10911): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter (10911): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
E/flutter (10911): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
E/flutter (10911): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
E/flutter (10911): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
E/flutter (10911): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
E/flutter (10911): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
E/flutter (10911): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)`

**Comment by Joseph-Nathan** [comment]
any news ?

**Comment by LecleVietnam** [comment]
I believe the issue stems from this package's inability to verify the video type from your link. This is because during initialization, the package needs to check the video type provided by your link
